import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import NavComponent from "./components/NavigateComponent";
import { Toaster } from "@/components/ui/sonner"

const nunitoMono = Nunito({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

// const geistMono = ({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "CC1981 - App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Custom Fonts */}
      </head>
      {/* meta */}
      <body className={`${nunitoMono.variable} antialiased`} >
        <NavComponent />
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
